/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosProductIdRouteImport } from './routes/productos.$productId'
import { Route as PedidoOrderNumberRouteImport } from './routes/pedido.$orderNumber'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosProductIdRoute = ProductosProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductosRoute,
} as any)
const PedidoOrderNumberRoute = PedidoOrderNumberRouteImport.update({
  id: '/pedido/$orderNumber',
  path: '/pedido/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/productos': typeof ProductosRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
  '/productos/$productId': typeof ProductosProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/productos': typeof ProductosRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
  '/productos/$productId': typeof ProductosProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/productos': typeof ProductosRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
  '/productos/$productId': typeof ProductosProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/carrito'
    | '/checkout'
    | '/contacto'
    | '/productos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/usuarios'
    | '/pedido/$orderNumber'
    | '/productos/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/carrito'
    | '/checkout'
    | '/contacto'
    | '/productos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/usuarios'
    | '/pedido/$orderNumber'
    | '/productos/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/carrito'
    | '/checkout'
    | '/contacto'
    | '/productos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/usuarios'
    | '/pedido/$orderNumber'
    | '/productos/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  ProductosRoute: typeof ProductosRouteWithChildren
  PedidoOrderNumberRoute: typeof PedidoOrderNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$productId': {
      id: '/productos/$productId'
      path: '/$productId'
      fullPath: '/productos/$productId'
      preLoaderRoute: typeof ProductosProductIdRouteImport
      parentRoute: typeof ProductosRoute
    }
    '/pedido/$orderNumber': {
      id: '/pedido/$orderNumber'
      path: '/pedido/$orderNumber'
      fullPath: '/pedido/$orderNumber'
      preLoaderRoute: typeof PedidoOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductosRouteChildren {
  ProductosProductIdRoute: typeof ProductosProductIdRoute
}

const ProductosRouteChildren: ProductosRouteChildren = {
  ProductosProductIdRoute: ProductosProductIdRoute,
}

const ProductosRouteWithChildren = ProductosRoute._addFileChildren(
  ProductosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  ProductosRoute: ProductosRouteWithChildren,
  PedidoOrderNumberRoute: PedidoOrderNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
