- name: Fix 404 for SPA
        # Cambiamos dist/client por .output/public
        run: cp .output/public/index.html .output/public/404.html || cp dist/client/index.html dist/client/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Intentamos subir .output/public, si no existe subirá dist/client
          path: './.output/public'
